# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Cathedral and the Bazaar
description: The classic essay by Eric S. Raymond
baseurl: "/CatB" # the subpath of your site, e.g. /blog
url: "https://mijowa.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
collections:
- chapters
source: ./src
